import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 4, y = 4 }
dynamic_padding = true

[font]
normal = { family = "IosevkaTerm Nerd Font", style = "Normal" }
size = 13.25

[mouse]
hide_when_typing = true
